### PR TITLE
[GROW-306] Clean up summary modal code

### PR DESCRIPTION
**Pull request by cheahenry**
Clean up summary modal code.

### CODE REVIEW

**Comment by dinostheo** [comment]
@cheahenry that's a good change, but I believe we don't use this anymore. I believe we never cleaned this logic. 

To give you some context, in the early days of the Plan Selector when we were downgrading we were displaying a warning banner to the user to let them know what they will be missing moving to a lower plan. 
However, we deprecated that warning on the server side, some time ago. I might be wrong, but I believe this functionality was there to find out if we need to display that warning or not.

**Comment by cheahenry** [comment]
@dinostheo yeah I just realized and just pushed some clean up :D

**Review by dinostheo — APPROVED** [review]
Thanks for the cleanup 🙌 
We should make it a habit and clean code that is not needed quickly, otherwise we forget 😄

**Comment by cheahenry** [comment]
I messed up my branch, gonna close this PR and open a new one 😅

**Pull request closed without merging**
